# Generated by Django 3.2.5 on 2021-07-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('pub_date', models.DateTimeField()),
                ('body', models.TextField(default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='JmApp/')),
                ('value', models.IntegerField(default=0)),
            ],
        ),
    ]
