# Generated by Django 3.2.5 on 2021-07-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JmApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='clickCount',
            field=models.IntegerField(default=0),
        ),
    ]
